### signup
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "username": "hi",
  "password": "1234"
}

### login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "hi",
  "password": "1234"
}

### test
GET http://localhost:8080/users/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoaSIsImF1dGgiOiJbZXguand0bmV3Lmdsb2JhbC5hdXRoLnVzZXJkZXRhaWxzLlVzZXJEZXRhaWxzSW1wbCQkTGFtYmRhLzB4MDAwMDAwNzAwMWJkODQ5MEA1MGM4ZTYyYV0iLCJleHAiOjE3NDA1NTc0NDksImlhdCI6MTc0MDU1Mzg0OX0.RGAt3vJFav4O0lUb6xh9Olbq22HKt_0lMbfmYeOidvz0Sw9I6eWbbcWvm0WtoGaEr2cHgsUd0xVkPStvveLJPA

### refresh
POST http://localhost:8080/users/refresh
Refresh-Token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoaSIsImF1dGgiOiJbZXguand0bmV3Lmdsb2JhbC5hdXRoLnVzZXJkZXRhaWxzLlVzZXJEZXRhaWxzSW1wbCQkTGFtYmRhLzB4MDAwMDAwMDgwMWJlMzEyOEAxOTQ3MTQ1M10iLCJleHAiOjE3NDE3NjA4MjQsImlhdCI6MTc0MDU1MTIyNH0.ubkHIoF6zBdOgmWMkhl4KUjNPBJHi0H4fUm93QYf6HFcDELaM4LFwOQk29NJNmVPmmuBlVHmeE1NK-U_6jp9XQ

### logout
POST http://localhost:8080/users/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoaSIsImF1dGgiOiJbZXguand0bmV3Lmdsb2JhbC5hdXRoLnVzZXJkZXRhaWxzLlVzZXJEZXRhaWxzSW1wbCQkTGFtYmRhLzB4MDAwMDAwMDYwMWJkZDQ5OEA1ZDkyOGNlOF0iLCJleHAiOjE3NDA1NTc5MzQsImlhdCI6MTc0MDU1NDMzNH0.hrgXi7Ht5HYiHThuA-THeQPRtE7AfYrI7gJeJoI4wM-0OfrTvziM1amauriF77EuPKKdDdIPisMHhiGjnZAiWw

